### ISSUE TITLE
Start without build 

### ISSUE THREAD

**Issue by MilosAleks** [e-hein/ng-spec-shot-reviewer#1]
other angular apps from C:\dev\dekra-gwm-frontend\dist
C:\Users\A...\AppData\Roaming\npm\node_modules\ng-spec-shot-reviewer\dist\server\app.js:70
            .reduce((allApps, moreApps) => allApps.concat(moreApps));
             ^

TypeError: Reduce of empty array with no initial value

**Comment by e-hein** [comment]
thanks for reporting

solved with version 1.0.2
